name: scheme_gen
description: a Dart package for generating Dart models and services from OpenAPI JSON.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables: 
  scheme_gen: main

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0
  args: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
